# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 9897
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /statics/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request
  profiles:
    active: test
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.tg.admin.modules.*.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: NOT_NULL
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
mbrex:
  cluster: false
  globalSessionTimeout: 3600
  redis:
    open: false

