spring:
  datasource:
    druid:
      url: "jdbc:mysql://119.45.240.149:3306/base_pritice?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC"
      username: root
      password: sunhua123...
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 600000
      remove-abandoned: true
      remove-abandoned-timeout: 180
      remove-abandoned-timeout-millis: 600000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 50
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        login-username: root
        login-password: yunaibo520
      query-timeout: 1000
      validation-query-timeout: 1
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: Wu123456789
    timeout: 6000ms
    jedis:
      pool:
        max-active: 500
        max-wait: -1ms
        max-idle: 200
        min-idle: 20
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: com.tg.api.entity
  global-config:
    db-config:
      id-type: AUTO
      field-strategy: not_null
    banner: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'